/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttackAttribution: typeof import('./src/components/AttackAttribution.vue')['default']
    BaselineAudit: typeof import('./src/components/BaselineAudit.vue')['default']
    DailyOperations: typeof import('./src/components/DailyOperations.vue')['default']
    DisasterRecovery: typeof import('./src/components/DisasterRecovery.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputTag: typeof import('element-plus/es')['ElInputTag']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Loading: typeof import('./src/components/Loading.vue')['default']
    PrivilegeRestriction: typeof import('./src/components/PrivilegeRestriction.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SituationalAwareness: typeof import('./src/components/SituationalAwareness.vue')['default']
    TrafficAnalysis: typeof import('./src/components/TrafficAnalysis.vue')['default']
    VulnerabilityManagement: typeof import('./src/components/VulnerabilityManagement.vue')['default']
  }
}
