/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttackAttribution: typeof import('./src/components/AttackAttribution.vue')['default']
    BaselineAudit: typeof import('./src/components/BaselineAudit.vue')['default']
    ChinaMap: typeof import('./src/components/ChinaMap.vue')['default']
    DailyOperations: typeof import('./src/components/DailyOperations.vue')['default']
    DisasterRecovery: typeof import('./src/components/DisasterRecovery.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Popover: typeof import('./src/components/ui/popover/Popover.vue')['default']
    PopoverContent: typeof import('./src/components/ui/popover/PopoverContent.vue')['default']
    PopoverTrigger: typeof import('./src/components/ui/popover/PopoverTrigger.vue')['default']
    PrivilegeRestriction: typeof import('./src/components/PrivilegeRestriction.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SituationalAwareness: typeof import('./src/components/SituationalAwareness.vue')['default']
    Textarea: typeof import('./src/components/ui/textarea/Textarea.vue')['default']
    TrafficAnalysis: typeof import('./src/components/TrafficAnalysis.vue')['default']
    VulnerabilityManagement: typeof import('./src/components/VulnerabilityManagement.vue')['default']
  }
}
